name: Docker Image CI

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t zatxm120/myproxy .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image to Docker Hub
      run: |
        docker push zatxm120/myproxy:latest
        docker tag zatxm120/myproxy:latest zatxm120/myproxy:${{ steps.get_version.outputs.VERSION }}
        docker push zatxm120/myproxy:${{ steps.get_version.outputs.VERSION }}
